/* 
   Copyright 2011 John Asmuth

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package main

import (
	"exp/template"
)
/*
var MakeCmdTemplate = template.MustParse(
	`# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG={Target}
GOFILES=\
{.repeated section GoFiles}	{@}\
{.end}

# gb: this is the local install
GBROOT={GBROOT}

# gb: compile/link against local install
GC+= -I $(GBROOT)/_obj
LD+= -L $(GBROOT)/_obj

# gb: default target is in GBROOT this way
command:

include $(GOROOT)/src/Make.cmd

# gb: copy to local install
$(GBROOT)/{BuildDirCmd}/$(TARG): $(TARG)
	mkdir -p $(dir $@); cp -f $< $@
command: $(GBROOT)/bin/$(TARG)
{.section LocalDeps}

# gb: local dependencies
{.repeated section LocalDeps}$(TARG): $(GBROOT)/{BuildDirPkg}/{@}.a
{.end}
{.end}
`,
	nil)
*/
var MakeCmdTemplateExp = func() *template.Template {
	t := template.New("MakeCmd")
	t, err := t.Parse(
		`# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG={{.Target}}
GOFILES=\
{{range .GoFiles}}	{{.}}\
{{end}}
# gb: this is the local install
GBROOT={{.GBROOT}}

# gb: compile/link against local install
GC+= -I $(GBROOT)/_obj
LD+= -L $(GBROOT)/_obj{{if .GOPATHS}}
# gb: compile/link against GOPATH entries{{range .GOPATHS}}
GC+= -I {{.}}/pkg/$(GOOS)_$(GOARCH)
LD+= -L {{.}}/pkg/$(GOOS)_$(GOARCH){{end}}{{end}}

# gb: default target is in GBROOT this way
command:

include $(GOROOT)/src/Make.cmd

# gb: copy to local install
$(GBROOT)/{{.BuildDirCmd}}/$(TARG): $(TARG)
	mkdir -p $(dir $@); cp -f $< $@
command: $(GBROOT)/bin/$(TARG)
{{if .LocalDeps}}
# gb: local dependencies{{if $BuildDirPkg=.BuildDirPkg}}
{{range .LocalDeps}}$(TARG): $(GBROOT)/{{$BuildDirPkg}}/{{.}}.a
{{end}}{{end}}{{end}}`)
	if err != nil {
		panic(err)
	}
	return t
}()
/*
var MakePkgTemplate = template.MustParse(
	`# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG={Target}
GOFILES=\
{.repeated section GoFiles}	{@}\
{.end}
{.section AsmObjs}

OFiles=\
{.repeated section AsmObjs}	{@}\
{.end}
{.end}
{.section CGoFiles}

CGOFILES=\
{.repeated section CGoFiles}	{@}\
{.end}
{.end}
{.section CObjs}

CGO_OFILES=\
{.repeated section CObjs}	{@}\
{.end}
{.end}

# gb: this is the local install
GBROOT={GBROOT}

# gb: compile/link against local install
GC+= -I $(GBROOT)/{BuildDirPkg}
LD+= -L $(GBROOT)/{BuildDirPkg}

{.section CopyLocal}
# gb: copy to local install
$(GBROOT)/{BuildDirPkg}/$(TARG).a: {BuildDirPkg}/$(TARG).a
	mkdir -p $(dir $@); cp -f $< $@
{.end}
package: $(GBROOT)/{BuildDirPkg}/$(TARG).a

include $(GOROOT)/src/Make.pkg
{.section LocalDeps}

# gb: local dependencies
{.repeated section LocalDeps}{BuildDirPkg}/$(TARG).a: $(GBROOT)/{BuildDirPkg}/{@}.a
{.end}
{.end}
`,
	nil)
*/
var MakePkgTemplateExp = func() *template.Template {
	t := template.New("MakePkg")
	t, err := t.Parse(
		`# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG={{.Target}}
GOFILES=\
{{range .GoFiles}}	{{.}}\
{{end}}{{if .AsmObjs}}

OFiles=\
{{range .AsmObjs}}	{{.}}\
{{end}}
{{end}}{{if .CGoFiles}}

CGOFILES=\
{{if .CGoFiles}}	{{.}}\
{{end}}
{{end}}{{if .CObjs}}

CGO_OFILES=\
{{range .CObjs}}	{{.}}\
{{end}}
{{end}}
# gb: this is the local install
GBROOT={{.GBROOT}}

# gb: compile/link against local install
GC+= -I $(GBROOT)/{{.BuildDirPkg}}
LD+= -L $(GBROOT)/{{.BuildDirPkg}}{{if .GOPATHS}}
# gb: compile/link against GOPATH entries{{range .GOPATHS}}
GC+= -I {{.}}/pkg/$(GOOS)_$(GOARCH)
LD+= -L {{.}}/pkg/$(GOOS)_$(GOARCH){{end}}{{end}}
{{if .CopyLocal}}
# gb: copy to local install
$(GBROOT)/{{.BuildDirPkg}}/$(TARG).a: {{.BuildDirPkg}}/$(TARG).a
	mkdir -p $(dir $@); cp -f $< $@
{{end}}
package: $(GBROOT)/{{.BuildDirPkg}}/$(TARG).a

include $(GOROOT)/src/Make.pkg
{{if .LocalDeps}}
# gb: local dependencies{{if $BuildDirPkg=.BuildDirPkg}}
{{range .LocalDeps}}{{$BuildDirPkg}}/$(TARG).a: $(GBROOT)/{{$BuildDirPkg}}/{{.}}.a
{{end}}{{end}}{{end}}`)
	if err != nil {
		panic(err)
	}
	return t
}()

type MakeData struct {
	Target      string
	GBROOT      string
	GoFiles     []string
	AsmObjs     []string
	CGoFiles    []string
	CObjs       []string
	LocalDeps   []string
	BuildDirPkg string
	BuildDirCmd string
	CopyLocal   bool
	GOPATHS     []string
}
