include $(GOROOT)/src/Make.inc
 
TARG=gb
GOFILES=\
	build.go\
	deps.go\
	gb.go\
	goinstall.go\
	make.go\
	pkg.go\
	gofmt.go\
	runext.go\
	util.go\
	files.go\
	usage.go\
	cgo.go\
	query.go\
	genmake.go\

include $(GOROOT)/src/Make.cmd
